---
# handlers file for init_nginx_proxy generate_ssl_certbot

- name: Generate SSL
  # include_tasks: generate_ssl.yml
  include_tasks: generate_ssl_certbot.yml


- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded