global:
  checkNewVersion: false
  sendAnonymousUsage: false

accessLog: {}

log:
  level: ERROR

api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  redisResolver:
    acme:
      email: "hourabdo89@.com"
      storage: "/etc/traefik/certs/acme.json"
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

providers:
  redis:
    endpoints:
      - "redis:6379"
