- name : Configure Redis
  template: 
    src: "redis.conf.j2"
    dest: "/etc/redis/redis.conf"
    owner: root
    group: root
    mode : 0644
    # I will notiy handler to start redis
    notify: Restart Redis