# tasks/main.yml
- name: Import apt update tasks
  import_tasks: apt_update.yml

- name: Import configure tasks
  import_tasks: configure.yml

- name: Import install tasks
  import_tasks: install.yml
