---
# tasks file for docker_stack
- name: Checkout A Docker App Where The Compose File That We Want To Build.
  block:
    - ansible.builtin.include_tasks: git_checkout_docker_pj.yml
    - ansible.builtin.include_tasks: create_needed_files_dirs.yml
    - ansible.builtin.include_tasks: install_docker_sdk.yml
    - ansible.builtin.include_tasks: build_stack.yml