- name: generate hello.txt file from a template
  hosts : webservers
  tasks :
    - name: Template a file to /root/hello.txt
      ansible.builtin.template:
        src: ./example.j2
        dest: /etc/nginx/proxies/{{ ansible_domain }}.conf