---
# vars file for java_app
home_dir: "/home/.akatsuki/software/{{ APP_NAME }}"
git_repo: "{{ GIT_REPO }}"
working_dir: "{{ (DIR_TO_PKG | default('') | string | length > 0) | ternary(home_dir ~ '/' ~ DIR_TO_PKG, home_dir) }}"

maven_version: "3.8.8"
maven_url: "https://downloads.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
