services:

  postgres:
    restart: unless-stopped
    image: postgres:16.2
    hostname: postgres
    volumes: 
     - semaphore-postgres:/var/lib/postgresql/data
    environment:
     POSTGRES_USER: ${DATABASE_USER}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
     POSTGRES_DB: ${DATABASE_NAME}
  # mysql:
  #   restart: unless-stopped
  #   image: mysql:8.0
  #   hostname: mysql
  #   volumes:
  #     - semaphore-mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  #     MYSQL_DATABASE: ${DATABASE_NAME}
  #     MYSQL_USER: ${DATABASE_USER}
  #     MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: ${DATABASE_USER}
      SEMAPHORE_DB_PASS: ${DATABASE_PASSWORD}
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${DATABASE_NAME}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
      TZ: UTC
    depends_on:
      - mysql
volumes:
  semaphore-postgres:
